services:
  backend:
    build: ./backend
    container_name: calorie_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL : postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET : ${SECRET}
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: calorie_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localost:8000
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: calorie_db
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data: 